config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root :to => "messages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/ancestry_node.rb
module AncestryNode
  extend ActiveSupport::Concern

  def tree
    nodes = subtree.arrange
    self.class.json_tree(nodes)
  end

  class_methods do
    def json_tree(nodes)
      nodes.map do |node, sub_nodes|
        item = node_iteratee(node)
        item.merge({
          id: node.id,
          parent_id: node.parent_id,
          children: json_tree(sub_nodes).compact,
        })
      end
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_ancestry

  include AncestryNode

  def self.node_iteratee(node)
    {
      name: node.name,
    }
  end
end

app/models/message.rb
class Message < ApplicationRecord
  has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.page(params[:page]).per(5)
    @message = Message.new
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new(:parent_id => params[:parent_id])
  end

  def create
    @message = Message.new(allow_params)
    if @message.save
      redirect_to messages_url
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_url
  end

  private

  def allow_params
    params.require(:message).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def nested_messages(messages)
    # 1. render(message) 会自动查找 _message.html.erb 的模板
    # 2. 并且把 message 这个数据传给这个模板
    messages.map do |message, sub_messages|
      render(message) + content_tag(:div, nested_messages(sub_messages), :class => "nested_messages")
    end.join.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsModuleSelfJoin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
  <%= f.hidden_field :parent_id %>
  <p>
    <%= f.label :content, "New Message" %><br />
    <%= f.text_area :content, :rows => 8, style: "width: 100%" %>
  </p>
  <p><%= f.submit "Post Message" %></p>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="created_at"><%= message.created_at.strftime("%B %d, %Y") %></div>
  <div class="content">
    <%= link_to message.content, message %>
  </div>
  <div class="actions">
    <%= link_to "Reply", new_message_path(:parent_id => message) %> |
    <%= link_to "Destroy", message, :confirm => "Are you sure?", :method => :delete %>
  </div>
</div>

app/views/messages/index.html.erb
<% title "Messages" %>

<%= nested_messages @messages.arrange(:order => :created_at) %>
<%= paginate @messages %>

<%= render "form" %>

app/views/messages/new.html.erb
<% title "New Message" %>

<%= render "form" %>

<p><%= link_to "Back to Messages", messages_path %></p>

app/views/messages/show.html.erb
<% title "Message" %>

<p>
  <!-- <%= @message.content %> -->
  <%= nested_messages @message.subtree.arrange(:order => :created_at) %>
</p>

<p><%= link_to "Back to All Messages", messages_path %></p>